env: "local"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "admin"
  password: "adminn"
storage:
  DBName: 0
  DBPassword: ""
  DBHost: "localhost"
  DBPort: "6379"
